shell = "C:/Program Files/nu/bin/nu.exe"

[env]
TERM = "xterm-256color"

[window]
title = "$"
dynamic_title = false

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", command = { program = "alacritty", args = ["--config-file", "D:\\scoop\\persist\\alacritty\\alacritty.toml", "--working-directory", "C:\\Users\\1\\Desktop" ] } },
]

[font]
size = 10.0

[font.bold]
family = "FantasqueSansMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FantasqueSansMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FantasqueSansMono Nerd Font"
style = "Italic"

[font.normal]
family = "FantasqueSansMono Nerd Font"
style = "Regular"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[colors.normal]
black = "#32344a"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#ad8ee6"
cyan = "#449dab"
white = "#787c99"

[colors.bright]
black = "#444b6a"
red = "#ff7a93"
green = "#b9f27c"
yellow = "#ff9e64"
blue = "#7da6ff"
magenta = "#bb9af7"
cyan = "#0db9d7"
white = "#acb0d0"
